Repository sendgrid/sendgrid-ruby, pull requests merged in 2018-10, with the labels that each got.

#343 Update USE_CASES.md
  USE_CASES.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update

#271 Add ability to impersonate subuser
  lib/sendgrid/client.rb
  test/sendgrid/test_sendgrid-ruby.rb
Labels: difficulty: medium, status: ready for deploy, type: sendgrid enhancement

#276 Codebase Improvement: Use attr_accessor instead of getters and setters
  lib/sendgrid/helpers/mail/content.rb
  lib/sendgrid/helpers/mail/email.rb
  lib/sendgrid/helpers/mail/mail.rb
Labels: difficulty: easy, status: ready for deploy, type: community enhancement

#277 FIX-274: Fix travis warning
  lib/sendgrid/helpers/mail/category.rb
  lib/sendgrid/helpers/stats/stats_response.rb
Labels: difficulty: easy, status: ready for deploy, type: bug

#278 [#197] Make SendGrid permissions management easy
  Rakefile
  examples/scopes/scopes.rb
  lib/sendgrid-ruby.rb
  lib/sendgrid/helpers/permissions/scope.rb
  lib/sendgrid/helpers/permissions/scopes.yml
  test/sendgrid/permissions/test_scopes.rb
Labels: difficulty: medium, status: ready for deploy, type: sendgrid enhancement

#284 make inclusion of sinatra optional
  CHANGELOG.md
  README.md
  lib/sendgrid/helpers/inbound/README.md
  lib/sendgrid/helpers/inbound/app.rb
  sendgrid-ruby.gemspec
Labels: difficulty: medium, status: ready for deploy, type: community enhancement

#303 Update readme tags and fix minor test failures
  README.md
  test/sendgrid/test_sendgrid-ruby.rb
Labels: difficulty: easy, status: ready for deploy, type: sendgrid enhancement
