Repository sendgrid/sendgrid-ruby, pull requests merged in 2020-08, with the labels that each got.

#344 docs: Update example.rb
  examples/helpers/mail/example.rb
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#432 chore: update GitHub branch references to use HEAD
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
  USAGE.md
  examples/mail/mail.rb
  lib/sendgrid/helpers/inbound/README.md
  lib/sendgrid/helpers/inbound/public/index.html
  lib/sendgrid/helpers/mail/README.md
  lib/sendgrid/helpers/settings/README.md
  mail_helper_v3.md
  twilio_sendgrid_logo.png
  use-cases/domain-authentication.md
  use-cases/email-statistics.md
Labels: status: code review request

#319 docs: Run all the *.md files through grammar.ly service and update accordingly
  CHANGELOG.md
  CONTRIBUTING.md
  TROUBLESHOOTING.md
  USAGE.md
  mail_helper_v3.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved
